# @backend = https://ap-openai-search-demo.azurewebsites.net/
###
@backend=https://app-backend-gn6fybhzdg24g.azurewebsites.net/

###
POST {{backend}}/chat HTTP/1.1
content-type: application/json

{
	"history": [
		{
			"user": "水素ハイブリッド電車とはなんですか"
		}
	],
	"approach": "rrr",
	"overrides": {
		"retrieval_mode": "hybrid",
		"semantic_ranker": false,
		"semantic_captions": false,
		"top": 1,
		"suggest_followup_questions": false
	}
}

###
POST {{backend}}/ask HTTP/1.1
content-type: application/json

{
	"question": "水素ハイブリッド電車とはなんですか",
	"approach": "rtr",
	"overrides": {
		"retrieval_mode": "hybrid",
		"semantic_ranker": true,
		"semantic_captions": false,
		"top": 1
	}
}


###
API Managementの動作確認
###

@apimanagement = https://apim-xxx.azure-api.net
###
POST {{apimanagement}}/api/ask HTTP/1.1
Content-Type: application/json

{
	"question": "水素ハイブリッド電車とはなんですか",
	"approach": "rtr",
	"overrides": {
		"retrieval_mode": "hybrid",
		"semantic_ranker": true,
		"semantic_captions": false,
		"top": 1
	}
}


###
POST {{apimanagement}}/api/ask HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: xxxxxxxxxxxxxxxx

{
	"question": "水素ハイブリッド電車とはなんですか",
	"approach": "rtr",
	"overrides": {
		"retrieval_mode": "hybrid",
		"semantic_ranker": true,
		"semantic_captions": false,
		"top": 1
	}
}